# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-left:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AsterisMono
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          template: classic
          filename: metrics-left.svg
          config_timezone: Asia/Shanghai

  github-metrics-right:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_indepth: no
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_rss: yes
          plugin_rss_limit: 3
          plugin_rss_source: https://noise.amono.me/rss.xml
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit

          token: ${{ secrets.METRICS_TOKEN }}
          user: AsterisMono
          base: ''
          template: classic
          filename: metrics-right.svg
          config_timezone: Asia/Shanghai